CREATE TABLE POST
(
     ID		    NUMBER,
     TITLE 		NVARCHAR2(100),
     WRITER 	NVARCHAR2(50),
     CONTENT	CLOB,
     REGDATE  	TIMESTAMP,
     HIT		NUMBER,
     "LIKE"		NUMBER,
     UNLIKE		NUMBER,
     HASHTAG    NVARCHAR2(100),
     PASSWORD	NVARCHAR2(100)
);

CREATE TABLE "COMMENT"
(
     ID		    NUMBER,
     CONTENT	NVARCHAR2(2000),
     REGDATE  	TIMESTAMP,
     WRITER	    NVARCHAR2(50),
     POST_ID	NUMBER,
     PASSWORD	NVARCHAR2(100)
);

CREATE SEQUENCE POST_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 2147483647
    NOCYCLE
    NOCACHE
    ORDER;
    
CREATE SEQUENCE COMMENT_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 2147483647
    NOCYCLE
    NOCACHE
    ORDER;

CREATE VIEW POST_VIEW AS SELECT * FROM (SELECT * FROM (SELECT * FROM POST ORDER BY REGDATE DESC));